### PR TITLE
#18962 Upgrade Datasaur Self-hosted RabbitMQ to 3.12

### PR DESCRIPTION
**Pull request by lucassusanto**
# 🌊 Changes <a href="#changes" id="changes" />

- Upgrade RabbitMQ to 3.12.13.

### CODE REVIEW

**Comment by tonoman3g** [comment]
@lucassusanto ini ada conflict, nanti tolong diresolve ya, dan setelah kita figure out how to enable the feature toggle automatically

**Comment by lucassusanto** [comment]
> @lucassusanto ini ada conflict, nanti tolong diresolve ya, dan setelah kita figure out how to enable the feature toggle automatically

Resolved

**Review by daniel-jeremia — APPROVED** [review]
LGTM

**Comment by daniel-jeremia** [comment]
@lucassusanto how to enable the feature toggle automatically
ini mksudnya apa cas?

**Comment by lucassusanto** [comment]
> @lucassusanto how to enable the feature toggle automatically ini mksudnya apa cas?

Waktu mau upgrade RabbitMQ dari 3.11 ke 3.12 ada [breaking change](https://datasaurlabels.slack.com/archives/C046WMD4H33/p1712050018634829?thread_ts=1712042516.822189&cid=C046WMD4H33). Di 3.11, semua feature flagsnya harus di-enabled. Kalau engga, nanti 3.12 engga mau jalan. How to enable the feature toggle automatically itu gimana caranya enable semua feature flags tanpa si customer bisa notice.

Tapi habis test upgrade 3.11 ke 3.12 ([related conversation](https://datasaurlabels.slack.com/archives/C046WMD4H33/p1712219087283149?thread_ts=1712042516.822189&cid=C046WMD4H33)), semua flagsnya udah otomatis di-enable sm 3.12 meskipun masih ada flag yang disabled di 3.11. Jadi enable the feature toggle automaticallynya se-simple ganti versi RabbitMQ dari 3.11 ke 3.12 @daniel-jeremia

**Pull request merged**
