### PR TITLE
Fix secrets not updating

### PR DESCRIPTION
**Pull request by michael-jong-ds**
Added `data` to secret configurations to force update the secrets

based off of this issue in helm charts
https://github.com/helm/helm/issues/12087

the discussion
https://datasaurlabels.slack.com/archives/C046WMD4H33/p1710833006999999?thread_ts=1710827910.431649&cid=C046WMD4H33

### CODE REVIEW

**Comment by tonoman3g** [comment]
@michael-jong-ds @daniel-jeremia please put the url of reference of the fixes in the PR description ya

**Comment by tonoman3g** [comment]
keep up lagi, ada conflict ya @michael-jong-ds

**Comment by michael-jong-ds** [comment]
kept up kak @tonoman3g please review again

**Review by daniel-jeremia — APPROVED** [review]
lgtm

**Review by tonoman3g — APPROVED** [review]

**Pull request merged**
